-- 2025.02.15
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE* s.SALES) TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE LIKE "2022-01%"
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY 1 ASC, 3 DESC;
