-- 2024-12-06
SELECT YEAR(YM) YEAR, ROUND(SUM(PM_VAL1)/COUNT(PM_VAL1),2) PM10, ROUND(SUM(PM_VAL2)/COUNT(PM_VAL2),2) "PM2.5"
    FROM AIR_POLLUTION
    WHERE LOCATION2 = "수원"
    GROUP BY YEAR
    ORDER BY YEAR ASC;