# -- 코드를 입력하세요
# SELECT ccc.CAR_ID, ccc.CAR_TYPE, FLOOR(ccc.DAILY_FEE*30* ((100-crcrp.DISCOUNT_RATE)/100)) as FEE
#     FROM CAR_RENTAL_COMPANY_CAR as ccc 
#         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS crcrp ON ccc.CAR_TYPE = crcrp.CAR_TYPE
#             WHERE ccc.CAR_TYPE IN ("트럭","세단")
#                 and crcrp.DURATION_TYPE="30일 이상"
#                 and ccc.CAR_ID NOT IN (
#                     SELECT DISTINCT crcrh.CAR_ID 
#                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh 
#                         WHERE crcrh.START_DATE<='2022-11-30' AND crcrh.END_DATE>='2022-11-01')
#                 and ccc.DAILY_FEE*30* ((100-crcrp.DISCOUNT_RATE)/100) >= 500000 
#                 and ccc.DAILY_FEE*30* ((100-crcrp.DISCOUNT_RATE)/100) < 2000000
#                     ORDER BY FEE DESC, ccc.CAR_TYPE ASC, ccc.CAR_ID desc;

SELECT A.CAR_ID, A.CAR_TYPE, CAST(A.DAILY_FEE*30*(1-B.DISCOUNT_RATE*0.01)AS SIGNED) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE=B.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT DISTINCT C.CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C 
    WHERE C.START_DATE<='2022-11-30' AND C.END_DATE>='2022-11-01'
)
AND A.CAR_TYPE IN('SUV', '세단') 
AND B.DURATION_TYPE = '30일 이상' 
AND A.DAILY_FEE*30*(1-B.DISCOUNT_RATE*0.01)>=500000 
AND A.DAILY_FEE*30*(1-B.DISCOUNT_RATE*0.01)<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;