-- 2025.01.09
# 틀림
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE 
#     HAVING FAVORITES = MAX(FAVORITES)
#     ORDER BY FOOD_TYPE DESC;


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    WHERE FOOD_TYPE = R.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;
