-- 2025.02.16
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT i.USER_ID) USERS
FROM USER_INFO i
JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;
    