# 2024-11-07
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,"%Y-%m-%d")START_DATE, DATE_FORMAT(END_DATE,"%Y-%m-%d") END_DATE, CASE WHEN DATEDIFF(END_DATE,START_DATE)>=29 THEN "장기 대여" ELSE "단기 대여" END RENT_TYPE 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE LIKE '2022-09%'
    ORDER BY 1 DESC;


# SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,"%Y-%m-%d")START_DATE, DATE_FORMAT(END_DATE,"%Y-%m-%d") END_DATE, CASE WHEN (DATE_FORMAT(END_DATE,"%Y-%m-%d") - DATE_FORMAT(START_DATE,"%Y-%m-%d"))>=29 THEN "장기 대여" ELSE "단기 대여" END RENT_TYPE 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE LIKE '2022-09%'
#     ORDER BY 1 DESC;


# SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,"%Y-%m-%d")START_DATE, DATE_FORMAT(END_DATE,"%Y-%m-%d") END_DATE, CASE WHEN DATE(DATE_FORMAT(END_DATE,"%Y-%m-%d")) - DATE(DATE_FORMAT(START_DATE,"%Y-%m-%d"))>=29 THEN "장기 대여" ELSE "단기 대여" END RENT_TYPE 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE LIKE '2022-09%'
#     ORDER BY 1 DESC;


# SELECT DATE("2024-11-07") - DATE("2023-11-07");
# SELECT DATEDIFF(DATE("2024-11-07"), DATE("2023-11-07"));
# SELECT (20241110)-(20241107);
# SELECT "2024"-"2021";

# SELECT "2024-11-07"-"2024-11-01";