-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, COUNT(DISTINCT OS.USER_ID) PURCHASED_USERS, 
ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE ("2021%")),1) PURCHASED_RATIO 
      FROM USER_INFO UI
    LEFT JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
    WHERE UI.JOINED LIKE ("2021%")
    GROUP BY DATE_FORMAT(OS.SALES_DATE, "%Y-%m") HAVING COUNT(OS.USER_ID) !=0
    ORDER BY 1 ASC, 2 ASC;