-- 2025.02.28
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT i.USER_ID) PURCHASED_USERS,
ROUND(COUNT(DISTINCT i.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE "2021%"),1) PUCHASED_RATIO
FROM USER_INFO i
    JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
WHERE YEAR(i.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH