-- 2025.02.04
SELECT p.ID, p.NAME, p.HOST_ID
    FROM PLACES p JOIN (SELECT HOST_ID, COUNT(*) CNT FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID)>1) AS c
        ON p.HOST_ID = c.HOST_ID
    ORDER BY p.ID ASC;