-- 코드를 입력하세요
SELECT fr.PRODUCT_ID, fr.PRODUCT_NAME, fr.PRICE*SUM(fo.AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT fr
    JOIN FOOD_ORDER fo ON fr.PRODUCT_ID = fo.PRODUCT_ID
    WHERE fo.PRODUCE_DATE LIKE "2022-05%"
    GROUP BY fr.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, fr.PRODUCT_ID ASC;