-- 2025.02.12
WITH temp AS (SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID)
SELECT r.PRODUCT_ID, r.PRODUCT_NAME, (r.PRICE*AMOUNT) TOTAL_SALES
    FROM FOOD_PRODUCT r JOIN temp t ON r.PRODUCT_ID = t.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;