-- 2025.02.25
WITH tmp AS (
    SELECT h.HISTORY_ID,
        CAR_TYPE,
        DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE)+1 DAYS,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >=90 THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >=30 THEN "30일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >=7  THEN "7일 이상"
            ELSE NULL
        END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR c 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
    WHERE CAR_TYPE = "트럭"
)
SELECT HISTORY_ID, FLOOR(tmp.DAILY_FEE * DAYS * (100- IFNULL(p.DISCOUNT_RATE,0))/100) FEE
FROM tmp LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON tmp.DURATION_TYPE = p.DURATION_TYPE AND p.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC;


