-- 2025.02.22
WITH RECURSIVE rc AS (SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 FROM rc WHERE HOUR<23)
SELECT rc.HOUR, COUNT(HOUR(o.DATETIME)) COUNT
FROM rc LEFT JOIN ANIMAL_OUTS o ON rc.HOUR = HOUR(o.DATETIME)
GROUP BY rc.HOUR
ORDER BY 1 ASC;