-- 2025.01.08
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
    WHERE STATUS = "DONE"
    GROUP BY USER_ID
    HAVING TOTAL_SALES >= 700000
    ORDER BY TOTAL_SALES ASC;