-- 2024-12-11
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
    FROM DEVELOPERS
    WHERE SKILL_CODE | (SELECT CODE FROM SKILLCODES WHERE NAME ="Python") = SKILL_CODE
        OR SKILL_CODE | (SELECT CODE FROM SKILLCODES WHERE NAME ="C#") = SKILL_CODE
    ORDER BY ID ASC;