-- 2024-12-12
SELECT ym.YEAR, (ym.max-SIZE_OF_COLONY) YEAR_DEV, ID
    FROM ECOLI_DATA ed JOIN 
                        (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) max FROM ECOLI_DATA GROUP BY YEAR) ym
                        ON YEAR(ed.DIFFERENTIATION_DATE) = ym.YEAR
    ORDER BY YEAR ASC, YEAR_DEV ASC;