-- 2026.04.22
SELECT fi.ID, fni.FISH_NAME, mfi.LENGTH FROM FISH_INFO fi 
JOIN ( 
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH FROM FISH_INFO GROUP BY FISH_TYPE
) mfi ON fi.FISH_TYPE = mfi.FISH_TYPE AND fi.LENGTH = mfi.LENGTH
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
ORDER BY fi.ID