-- 2026.04.20
SELECT h.TOTAL SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL FROM HR_EMPLOYEES he 
    JOIN (SELECT EMP_NO, SUM(SCORE) TOTAL FROM HR_GRADE GROUP BY EMP_NO ORDER BY TOTAL DESC LIMIT 1) h ON he.EMP_NO = h.EMP_NO
    
    

