-- 2024-12-08
WITH grade2022 AS (
    SELECT EMP_NO, SUM(SCORE) totalScore
    FROM HR_GRADE
    GROUP BY EMP_NO)
SELECT totalScore SCORE, he.EMP_NO, EMP_NAME, POSITION, EMAIL
    FROM HR_EMPLOYEES he JOIN grade2022 g ON he.EMP_NO = g.EMP_NO
    WHERE totalScore IN (SELECT MAX(totalScore) FROM grade2022);