-- 2025.01.09
SELECT hd.DEPT_ID, DEPT_NAME_EN, ROUND(AVG_DEPT.avg_sal,0) AVG_SAL
    FROM HR_DEPARTMENT hd
    JOIN (SELECT DEPT_ID, AVG(SAL) avg_sal FROM HR_EMPLOYEES GROUP BY DEPT_ID) AVG_DEPT
    ON hd.DEPT_ID = AVG_DEPT.DEPT_ID
    ORDER BY AVG_SAL DESC;
    
    