-- 2026.04.23
SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(e.AVG_SAL, 0) 
FROM  HR_DEPARTMENT d
JOIN (
    SELECT DEPT_ID, AVG(SAL) AVG_SAL FROM HR_EMPLOYEES GROUP BY DEPT_ID
) e ON d.DEPT_ID = e.DEPT_ID
ORDER BY e.AVG_SAL DESC;