-- 2025.01.07
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
    FROM BOOK b JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
    WHERE SALES_DATE LIKE "2022-01%"
    GROUP BY CATEGORY
    ORDER BY CATEGORY ASC;
    
    
    