-- 2025.02.11
WITH MAX_FOOD_PRODUCT AS (
    SELECT CATEGORY,
        PRICE,
        MAX(PRICE) OVER (PARTITION BY CATEGORY) MAX_PRICE,
        PRODUCT_NAME
    FROM FOOD_PRODUCT
)
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
    FROM MAX_FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국','김치','식용유') AND PRICE = MAX_PRICE
    ORDER BY MAX_PRICE DESC;