-- 2025.02.05
# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# WHERE FISH_TYPE IN (
#     SELECT FISH_TYPE
#     FROM (
#         SELECT ID, FISH_TYPE, 
#                CASE 
#                    WHEN LENGTH < 10 THEN 10
#                    WHEN LENGTH IS NULL THEN 0
#                    ELSE LENGTH
#                END AS ADJ_LENGTH
#         FROM FISH_INFO
#     ) AS q
#     GROUP BY FISH_TYPE
#     HAVING AVG(ADJ_LENGTH) >= 33
# )
# GROUP BY FISH_TYPE
# ORDER BY FISH_TYPE ASC;

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, fi.FISH_TYPE
FROM FISH_INFO fi
JOIN (
    SELECT DISTINCT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(
        CASE WHEN LENGTH < 10 THEN 10
            WHEN LENGTH IS NULL THEN 0
            ELSE LENGTH
        END) >=33
) AS Filtered_FISH_INFO ON fi.FISH_TYPE = Filtered_FISH_INFO.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC;